test_name: "cdreamer_multiagent_nonstationary"

# num_agents: 1
# target_position: 1

architecture: "cDreamer"
window_in: 2
window_out: 1

map_mode: "Std"

start_n: 0
n: 1
set_n: 1

random_seed: 10000
noise_std: 0.0

start_train_steps: 0
n_train_steps: 100000
n_test_laps: 50

map_name: "f1_esp"
reward: "Cth"

max_speed: 6

lr: 0.00003
gamma: 0.85
ma_info: [0.15, 0.15, 0.3, 0.3]

runs:
  - adversaries: ['PP']
    num_agents: 2
    target_position: 2
  # - adversaries: ['PP', 'PP', 'PP']
  #   num_agents: 4
  #   target_position: 4






