
test_name: "Cth_speeds"

num_agents: 2
target_position: 2

architecture: "DreamerV2"
window_in: 15
window_out: 10

train_mode: "Std"
test_mode: "Std"

n: 4
set_n: 1

random_seed: 10000

n_train_steps: 100000
# n_train_steps: 200
n_test_laps: 20
# n_test_laps: 50

map_name: "f1_esp"
reward: "Cth"

adversaries:
  - architecture: DispExt
 

runs:
  - max_speed: 7
  - max_speed: 8






