
test_name: "dreamerv3_lr"

num_agents: 2
target_position: 2

architecture: "DreamerV3"
window_in: 2
window_out: 1

map_mode: "Std"

n: 2
set_n: 1

random_seed: 10000
noise_std: 0.0

n_train_steps: 10000
n_test_laps: 20

map_name: "f1_esp"
reward: "Cth"

max_speed: 5

gamma: 0.85
adversaries: ['PP']
ma_info: [0.0, 0.0, 0.0, 0.0]


runs:
  - lr: 0.00001
  - lr: 0.0001
  - lr: 0.001






