test_name: "SAC_lr"

num_agents: 2
target_position: 2

architecture: "SAC"
window_in: 2
window_out: 1

map_mode: "Std"

n: 3
set_n: 1

random_seed: 10000
noise_std: 0.0

n_train_steps: 50000
n_test_laps: 50

map_name: "f1_esp"
reward: "Cth"

max_speed: 5

gamma: 0.85
adversaries: ['PP'] 
ma_info: [0.0, 0.0, 0.0, 0.0]


runs:
  - lr: 0.0001
  - lr: 0.0005
  - lr: 0.001
  - lr: 0.005
