test_name: "SAC_lr"

num_agents: 3
target_position: 2

architecture: "SAC"
window_in: 2
window_out: 1

map_mode: "Std"

n: 5
set_n: 1

random_seed: 10000

# n_train_steps: 100000
n_train_steps: 20000
n_test_laps: 50

map_name: "f1_esp"
reward: "Cth"

max_speed: 5

adversaries: ['PP', 'PP'] 

runs:
  - lr: 0.0001
  - lr: 0.0005
  - lr: 0.001
  - lr: 0.005


# runs:
  # - max_speed: 7
  # - max_speed: 8






