test_name: "SAC_singleagent"

num_agents: 1
target_position: 1

architecture: "SAC"
window_in: 2
window_out: 1

map_mode: "Std"

n: 3
set_n: 1

random_seed: 10000
noise_std: 0.0

n_train_steps: 100000
n_test_laps: 50

map_name: "f1_esp"
reward: "Cth"

max_speed: 6

lr: 0.001
gamma: 0.85
ma_info: [0.0, 0.0, 0.0, 0.0]

runs:
  - adversaries: []
